version: "3"
services:
  wellnessui:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - frontend

networks:
  frontend:
    driver: bridge